# Generated by Django 3.0.3 on 2020-06-04 08:45

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'ActivityPeriod',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', timezone_field.fields.TimeZoneField()),
                ('activity_periods', models.ManyToManyField(to='User.ActivityPeriod')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
